---
title: "Research and Publications"
---

I study American Politics with an edge towards International Relations. I largely focus on the role of one's socialization, context, and social networks in shaping political attitudes and behaviors. My research can be encapsulated in several broad categories as displayed in the Contents on the right. I go into greater detail in each section below. I also include publications, working papers and information on the trajectory for future work in this area.

My research has been generously funded by the Institute for Humane Studies at George Mason University and the Department of Political Science at Northwestern University.

# American Civil-Military Relations and Military Professionalism

## Dissertation Project

My dissertation is a book project that examines the role of the Reserve Officer Training Corps (ROTC) and service academy programs in shaping students' political and social attitudes compared to civilian students who do not undergo this training. In addition, I examine how the public views ROTC programs and how such confidence in ROTC translates to broader support for the US military. In short, I ask three main questions:

1. How do the political and social attitudes of students in a military officer training program (like ROTC or service academy) compare to their civilian counterparts? 
2. How do these attitudes develop across the course of the college career? 
3. How does the public perceive these programs and how does it correlate with their attitudes about the American military?

## Publications

<ol reversed>
<li> **Lin, J.**, & Lunz Trujillo, K. (2024). Urban-Rural Differences in Respect for the Norms of American Civil-Military Relations. *American Politics Research*. <br>
<a role="button" href="Files/Papers/CMR_APR_2024.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.1177/1532673X241263085" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>
</ol>

## Working Papers

<ol reversed>
<li>**Lin, J.** (Under Review). Training Citizen Officers: Political Socialization from a Military Education </li>
<li> **Lin, J.**, Spindel, J., & Lunz Trujillo, K. (Manuscript in Preparation) Americans’ Conceptualization of the Reserve Officer Training Corps Programs
</ol>

# Urban-Rural Political Attitudes and Behavior

I am interested in the role of context, specifically based in one's place of residence, on political attitudes and behavior. In this set of papers, I examine urban-rural differences in political attitudes, participation, values, and more.

## Publications

<ol reversed>
<li> Lunz Trujillo, K. & **Lin, J.** (2025). Real or Imagined? American Urban-Rural Differences in Political Values. *Political Research Quarterly*.</li>
<li> **Lin, J.**, & Lunz Trujillo, K. (2023). Are Rural Attitudes Just Republican? *Political Science Research and Methods.* <br>
<a role="button" href="Files/Papers/Republican_PSRM_2023.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.7910/DVN/2MZE9D" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai open-materials >}} Data and Code </a> 
<a role="button" href="https://doi.org/10.1017/psrm.2023.48" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> **Lin, J.**, & Lunz-Trujillo, K. (2022) Urban-Rural Differences in Non-Voting Political Behavior. *Political Research Quarterly 76*(2), 851–868. <br>
<a role="button" href="Files/Papers/NonVoting_PRQ_2023.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.7910/DVN/UIUV3U" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai open-materials >}} Data and Code </a>
<a role="button" href="https://doi.org/10.1177/10659129221119195" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

</ol>


## Working Papers

<ol reversed>
<li> **Lin, J.**, & Lunz Trujillo, K. (Under Review). Urban-Rural Residency, Place Identity, and Affective Polarization in the United States </li>
<li> Pippert, C. H., **Lin, J.**, & Lunz Trujillo, K. (Manuscript in Preparation) Personal Considerations in Political Participation. </li>
<ol>

# Partisanship, Polarization and American Democracy

Another major factor determining one's political attitudes and behavior is rooted in partisanship and political polarization. In this aspect of my research agenda, I examine the role of partisanship in shaping moral values, demands for representation, attitudes, partisan animosity and more.

## Publications

### Peer Reviewed Journal Articles

<ol reversed>
<li> **Lin, J.** (2024). From Barack Obama to Donald Trump: The Evolution of Moral Appeals in National Conventions. *Journal of Language and Politics*. <br>
<a role="button" href="Files/Papers/NatCon_JLP_2024.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a> 
<a role="button" href="https://doi.org/10.7910/DVN/MZUCUA" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai open-materials >}} Data and Code </a>
<a role="button" href="https://doi.org/10.1075/jlp.22173.lin" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Christenson, D. P., **Lin, J.**, & Makse, T. (2021). Ask Only What Your Country Can Do for You: Group Interests, Constituency Characteristics, and Demands for Representation. *American Politics Research 49*(1), 17 - 29. <br>
<a role="button" href="Files/Papers/DFR_APR_2021.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a> 
<a role="button" href="https://doi.org/10.1177/1532673X20961028" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

</ol>

### Book Chapters

<ol reversed>
<li> **Lin, J.**, & Druckman, J. N. (Forthcoming) "Party Polarization and COVID-19". In Monica K. Miller eds. The Social Science of the COVID-19 Pandemic: A Call to Action for Researchers. Oxford University Press.</li>
</ol>

# Downstream Effects of the COVID-19 Pandemic

Finally, current events, like the COVID-19 Pandemic in 2020, shapes the context in which we interpret political issues and form our opinions. I am a member of the [COVID States Project](https://www.covidstates.org/) and I collaborate with researchers from Harvard, Northeaster, Rutgers and Northwestern to identify the effects that the COVID-19 Pandemic had on personal well-being, political outlook, civic engagement and more.

## Publications

### Peer-Reviewed Journal Articles

#### Political Science

<ol reversed>
<li> Safarpour, A. C., Lunz Trujillo, K., Green, J., Pippert, C., **Lin, J.**, & Druckman, J. N. (2024). Divisive or Descriptive: How Americans Understand Critical Race Theory. *Journal of Race and Ethnic Politics*.<br>
<a role="button" href="Files/Papers/CRT_JEPS_2023.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.1017/rep.2023.39" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Lunz Trujillo, K., Green, J., Safarpour, A. C., Lazar, D., **Lin, J.**, & Motta, M. (2024). COVID-19 Spillover Effects onto General Vaccine Attitudes. *Public Opinion Quarterly*. <br>
<a role="button" href="Files/Papers/Spillover_POQ_2024.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.1093/poq/nfad059" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Baum, M. A., Druckman, J. N., Simonson, M. D., **Lin, J.**, & Perlis, R. H. (2023). The Political Consequences of Depression: How Conspiracy Beliefs, Participatory Inclinations, and Depression Affect Support for Political Violence. *American Journal of Political Science*. <br>
<a role="button" href="Files/Papers/Depression_AJPS_2023.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.1111/ajps.12827" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Green, J., Druckman, J. N., Baum, M. A., Lazer, D., Ognyanova, K., Simonson, M. D. **Lin, J.**, Santillana, M., & Perlis, R. H. (2022). Using General Messages to Persuade on a Politicized Scientific Issue. *British Journal of Political Science, 53*(2), 698-706. <br>
<a role="button" href="Files/Papers/VaxMes_BJPS_2022.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.1017/S0007123422000424" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>
</ol>

#### Other Social Science

<ol reversed>
<li> Solomonov, N., Green, J., Quintana, A., **Lin, J.**, Ognyanova, K., Santillana, M., Druckman, J. N., Baum, M., Lazer, D., Gunning, F. M., & Perlis, R. H. (2023). A 50-state survey study of thoughts of suicide and social isolation among older adults in the United States. *Journal of Affective Disorders, 334*, 43 - 49. <br>
<a role="button" href="https://doi.org/10.1016/j.jad.2023.04.038" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Perlis, R. H., Simonson, M., Green, J., **Lin, J.**, Safarpour, A., Lunz Trujillo, K., Quintana, A., Chwe. H., Della Volpe, J., Ognyanova, K., Santillana, M., Druckman, J. N., Lazer, D., & Baum, M. (2022). Prevalence of Firearm Ownership Among Individuals With Major Depressive Symptoms. *JAMA Network Open, 5*(3):e223245. <br>
<a role="button" href="Files/Papers/FirearmJAMA.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="http://doi.org/10.1001/jamanetworkopen.2022.3245" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Perlis, R. H., Ognyanova, K., Santillana, M., **Lin, J.**, Druckman, J. N., Lazer, D., Green, J., Simonson, M., Baum, M., & Della Volpe, J. (2022). Association of Major Depressive Symptoms With Endorsement of COVID-19 Vaccine Misinformation Among US Adults. *JAMA Network Open, 5*(1):e2145697. <br>
<a role="button" href="Files/Papers/VaxMisinfoJAMA.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="http://doi.org/10.1001/jamanetworkopen.2021.45697" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Perlis, R. H., Green, J., Simonson, M., Ognyanova, K., Santillana, M., **Lin, J.**, Quintana, A., Chwe. H., Druckman, J. N., Lazer, D., Baum, M., & Della Volpe, J. (2021). Association Between Social Media Use and Self-reported Symptoms of Depression in US Adults. *JAMA Network Open, 4*(11):e2136113. <br>
<a role="button" href="Files/Papers/SocialMediaJAMA.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="http://doi.org/10.1001/jamanetworkopen.2021.36113" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a> <br><br>
</li>

<li> Perlis, R. H., Ognyanova, K., Quintana, A., Green, J., Santillana, M., **Lin, J.**, Druckman, J. N., Lazer, D., Simonson, M., Baum, M., & Chwe. H. (2021). Gender-specificity of resilience in major depressive disorder. *Depression and Anxiety, 38*, 1026– 1033. <br>
<a role="button" href="Files/Papers/Gender_DA.pdf" type="button" class="btn btn-outline-secondary btn-xs"> {{< bi file-pdf >}} PDF </a>
<a role="button" href="https://doi.org/10.1002/da.23203" type="button" class="btn btn-outline-secondary btn-xs"> {{< ai doi >}} DOI </a><br><br>
</li>
</ol>





